# ____________BUCKET____________
resource "aws_s3_bucket" "raw_data" {
  bucket = var.bucket_name
}

# ____________IAM____________
# specifies permissions that a role can execute
data "aws_iam_policy_document" "iam_permissions_policy" {
  statement {
    actions = [
      "s3:GetObject", # retrieve objects from a bucket
      "s3:GetObjectVersion",
      "s3:PutObject",   # add an obj to a bucket
      "s3:DeleteObject" # rm a null version 
    ]
    resources = ["${local.bucket_arn}/**"]
  }
  statement {
    actions = [
      "s3:ListBucket",       # lists objects in a bucket
      "s3:GetBucketLocation" # returns an s3 region
    ]
    resources = ["${local.bucket_arn}"]
  }
}

# creates a policy with permissions defined above
resource "aws_iam_policy" "s3_read" {
  name   = "policy-s3-read"
  policy = data.aws_iam_policy_document.iam_permissions_policy.json
}

# an access to authorized account id
data "aws_caller_identity" "current" {}

# who can assume the 'snowflake_uploader' role
data "aws_iam_policy_document" "iam_trust_policy" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "AWS"
      identifiers = [local.account_id] # dummy value
    }
    condition {
      test     = "StringEquals"
      variable = "sts:ExternalId"
      values   = ["xxxxxxxx"] # dummy value  
    }
  }
}

# 'snowflake-uploader' role
resource "aws_iam_role" "snowflake" {
  name               = local.iam_role_name
  description        = "Role that will upload the most recent .csv file to Snowflake"
  assume_role_policy = data.aws_iam_policy_document.iam_trust_policy.json
  lifecycle {
    ignore_changes = [assume_role_policy] # ignore changes made later on inside a ./terraform sub dir 
  }
}

# role can interact with a bucket
resource "aws_iam_role_policy_attachment" "s3_prermissions_policy_for_snowflake" {
  role       = aws_iam_role.snowflake.name
  policy_arn = aws_iam_policy.s3_read.arn
}

# ____________CLOUDWATCH ALARM____________
resource "aws_cloudwatch_metric_alarm" "size_alarm" {
  depends_on        = [aws_s3_bucket.raw_data]
  alarm_name        = "bucket_size_alarm"
  alarm_description = "Alarm when S3 bucket size exceeds "
  namespace         = "AWS/S3"
  metric_name       = "BucketSizeBytes"
  dimensions = {
    StorageType = "StandardStorage"
    BucketName  = var.bucket_name
  }
  statistic           = "Maximum"
  period              = 86400 # 1 day
  comparison_operator = "GreaterThanOrEqualToThreshold"
  threshold           = 50000 # 50kB
  evaluation_periods  = 1     # condition must be met 1 time for an alarm to go off
  alarm_actions       = [aws_sns_topic.size_reached.arn]
}

# ____________SNS TOPIC____________
resource "aws_sns_topic" "size_reached" {
  name = "bucket_size_topic"
}

resource "aws_sns_topic_subscription" "size_reached_subsciption" {
  topic_arn = aws_sns_topic.size_reached.arn
  protocol  = "email"
  endpoint  = var.cloudwatch_email == "" ? "ravexeh257@fanicle.com" : var.cloudwatch_email # dummy e-mail generated by temp-mail.org
}