name: 'transform'
version: '1.0.0'


profile: 'transform'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  'dbt_date:time_zone': 'Europe/Warsaw' #TODO - make custom

models:
  transform:
    snowflake_warehouse: WH
    staging:
      +materialized: view
    marts:
      +materialized: table
